#!/usr/bin/env python3

import src.iso_dl as iso_dl

iso_dl.main()

raise SystemExit

from sys import argv

if not argv[1:]:
    for distro in iso_dl.DISTROS:
        print(distro)

elif (name := argv[1].lower()) in iso_dl.DISTROS:
    p = lambda k, v: print(f"{k.ljust(12).upper()} {v}")
    p("version", iso_dl.DISTROS[name].version)
    for (k, v) in iso_dl.DISTROS[name]["amd64"].items():
        if v:
            p(k, v)

else:
    print(f"Invalid distro: {name}")
